In [1]:
import pandas as pd

In [2]:
all_names = list(set(pd.read_excel('temp_data.xlsx', sheet_name='Date_Availability')['Names']))

In [3]:

cols = [
    'SOUND #1 (M)',
    'PROJECTIONIST (M)',
    'COORDINATOR (B)',
    'LIVESTREAM #1 (B)',
    'SOUND #1 (B)',
    'SOUND #2 (B)',
    'PROJECTIONIST (B)'
    ]
df = pd.DataFrame(columns=cols, index=all_names, data=False)


def update_skill_df(df:pd.DataFrame, role:str, members:list)->None:
    df.loc[members, role] = True
    return df

df = update_skill_df(df, 'SOUND #1 (M)', ['SINGYE', 'WONSEN', 'SHERMAN'])
df = update_skill_df(df, 'PROJECTIONIST (M)', ['CHEE FS', 'FRED KWAN', 'IAN MING', 'LAWRENCE', 'PAMELA CHEONG', 'HONGTO', 'STEVEN', 'ROBIN'])
df = update_skill_df(df, 'COORDINATOR (B)', ['WEI XUAN', 'YU XUAN', 'ANDREW', 'FAM', 'TITUS', 'JURINA', 'BENEDICT'])
df = update_skill_df(df, 'LIVESTREAM #1 (B)', ['SIAW ENG', 'HING GEE', 'SWEE GEOK', 'MU TIAN', 'TIMOTHY', 'YU TANG', 'ZHI QIAN'])
df = update_skill_df(df, 'SOUND #1 (B)', ['JAIRUS', 'JEFFERY', 'SHAWN', 'JEREMY', 'MATHIAS', 'TIMOTHY'])
df = update_skill_df(df, 'SOUND #2 (B)', ['JAIRUS', 'JEFFERY', 'SHAWN', 'JEREMY', 'MATHIAS', 'TIMOTHY'])
df = update_skill_df(df, 'PROJECTIONIST (B)', ['BENEDICT', 'ELLY', 'JURINA', 'MAVIS', 'SIAW ENG', 'TIMOTHY'])

df = df.sort_index()

df = df.drop(index='BENEDICT')
df = df.drop(index='MAVIS')
df = df.drop(index='ROBIN')
df = df.reset_index(names=['Names'])
display(df)
df.to_excel('skills_mapping.xlsx')

,Names,SOUND #1 (M),PROJECTIONIST (M),COORDINATOR (B),LIVESTREAM #1 (B),SOUND #1 (B),SOUND #2 (B),PROJECTIONIST (B)
0,ANDREW,False,False,True,False,False,False,False
1,CHEE FS,False,True,False,False,False,False,False
2,ELLY,False,False,False,False,False,False,True
3,FAM,False,False,True,False,False,False,False
4,FRED KWAN,False,True,False,False,False,False,False
5,HING GEE,False,False,False,True,False,False,False
6,HONGTO,False,True,False,False,False,False,False
7,IAN MING,False,True,False,False,False,False,False
8,JAIRUS,False,False,False,False,True,True,False
9,JEFFERY,False,False,False,False,True,True,False
10,JEREMY,False,False,False,False,True,True,False
11,JURINA,False,False,True,False,False,False,True
12,LAWRENCE,False,True,False,False,False,False,False
13,MATHIAS,False,False,False,False,True,True,False
14,MU TIAN,False,False,False,True,False,False,False
15,PAMELA CHEONG,False,True,False,False,False,False,False
16,SHAWN,False,False,False,False,True,True,False
17,SHERMAN,True,False,False,False,False,False,False
18,SIAW ENG,False,False,False,True,False,False,True
19,SINGYE,True,False,False,False,False,False,False
20,STEVEN,False,True,False,False,False,False,False
21,SWEE GEOK,False,False,False,True,False,False,False
22,TIMOTHY,False,False,False,True,True,True,True
23,TITUS,False,False,True,False,False,False,False
24,WEI XUAN,False,False,True,False,False,False,False
25,WONSEN,True,False,False,False,False,False,False
26,YU TANG,False,False,False,True,False,False,False
27,YU XUAN,False,False,True,False,False,False,False
28,ZHI QIAN,False,False,False,True,False,False,False

In [93]:
flawed_solution_df = pd.read_csv('flawed_final_solution.csv', index_col=0)
good_solution_df = pd.read_csv('final_solution.csv', index_col=0)
good_solution_df.head()

,Job,2025-03-01,2025-03-08,2025-03-15,2025-03-22,2025-03-29,2025-04-05,2025-04-12,2025-04-19,2025-04-26,2025-05-03,2025-05-10,2025-05-17,2025-05-24
0,Coordinator(M),WeiXuan,YeapYuXuan,YeapYuXuan,FamHanFeng,YeapYuXuan,WeiXuan,AndrewCheam,YeapYuXuan,AndrewCheam,WeiXuan,YeapYuXuan,WeiXuan,AndrewCheam
1,Livestream#1(M),YapMengHong,YapMengHong,NaN,YapMengHong,YapMengHong,NaN,YapMengHong,YapMengHong,NaN,YapMengHong,NaN,YapMengHong,YapMengHong
2,Sound#1(M),ShermanLee,SingYe,ShermanLee,ShermanLee,SingYe,SingYe,ShermanLee,SingYe,SingYe,WonSen,SingYe,SingYe,ShermanLee
3,Sound#2(M),WonSen,WonSen,SingYe,WonSen,WonSen,ShermanLee,WonSen,WonSen,ShermanLee,ShermanLee,WonSen,ShermanLee,WonSen
4,Projectionist(M),HongTao,FredKwan,CheeFookSeng,IanMing,HongTao,CheeFookSeng,CheeFookSeng,IanMing,FredKwan,FredKwan,HongTao,FredKwan,IanMing

In [101]:
skills_df = pd.read_csv('skills_mapping.csv', index_col=0)
skills_df = skills_df.set_index('Names')
skills_df.head()

,Coordinator(B),Livestream#1(B),Livestream#2(B),Sound#1(B),Sound#2(B),Projectionist(B),Coordinator(M),Livestream#1(M),Sound#1(M),Sound#2(M),Projectionist(M)
Names,,,,,,,,,,,
FamHanFeng,True,True,True,False,True,False,True,False,False,False,False
ShawnHew,False,True,True,True,True,False,False,False,False,False,False
TitusLeong,True,False,False,True,True,False,False,False,False,False,False
Jeffrey,False,False,False,True,True,False,False,False,False,False,False
JeremyFam,False,False,False,True,True,False,False,False,False,False,False

In [107]:
flawed_solution_df.loc[0, '2025-03-01'] = 'Jeffrey'
flawed_solution_df

,Job,2025-03-01,2025-03-08,2025-03-15,2025-03-22,2025-03-29,2025-04-05,2025-04-12,2025-04-19,2025-04-26,2025-05-03,2025-05-10,2025-05-17,2025-05-24
0,Coordinator(M),Jeffrey,WeiXuan,YeapYuXuan,AndrewCheam,AndrewCheam,WeiXuan,AndrewCheam,YeapYuXuan,FamHanFeng,WeiXuan,YeapYuXuan,FamHanFeng,YeapYuXuan
1,Livestream#1(M),YapMengHong,YapMengHong,NaN,YapMengHong,NaN,YapMengHong,YapMengHong,NaN,YapMengHong,YapMengHong,NaN,YapMengHong,YapMengHong
2,Sound#1(M),ShermanLee,WonSen,WonSen,SingYe,SingYe,WonSen,SingYe,ShermanLee,ShermanLee,WonSen,SingYe,ShermanLee,SingYe
3,Sound#2(M),WonSen,ShermanLee,SingYe,ShermanLee,WonSen,SingYe,WonSen,WonSen,SingYe,ShermanLee,WonSen,SingYe,ShermanLee
4,Projectionist(M),FredKwan,FredKwan,IanMing,IanMing,HongTao,CheeFookSeng,CheeFookSeng,IanMing,FredKwan,CheeFookSeng,IanMing,HongTao,HongTao
5,Coordinator(B),TimothyKwan,Jurina,TimothyKwan,Jurina,WeiXuan,Jurina,TitusLeong,AndrewCheam,Jurina,YeapYuXuan,Jurina,AndrewCheam,WeiXuan
6,Livestream#1(B),MuTian,CheamHingGee,TengZhiQian,HungSweeGeok,KooYuTang,MuTian,HungSweeGeok,CheamHingGee,KooYuTang,CheamHingGee,MuTian,KooYuTang,TengZhiQian
7,Livestream#2(B),TengZhiQian,KooYuTang,CheamHingGee,TengZhiQian,HungSweeGeok,KooYuTang,MuTian,MuTian,CheamHingGee,TengZhiQian,FamHanFeng,HungSweeGeok,HungSweeGeok
8,Sound#1(B),JairusChong,ShawnHew,ShawnHew,Jeffrey,JeremyFam,Jeffrey,JairusChong,TitusLeong,TitusLeong,ShawnHew,JairusChong,JeremyFam,JeremyFam
9,Sound#2(B),ShawnHew,FamHanFeng,TitusLeong,ShawnHew,TitusLeong,FamHanFeng,JeremyFam,JairusChong,JeremyFam,Jeffrey,Jeffrey,JairusChong,Jeffrey
10,Projectionist(B),HoSiawEng,TimothyKwan,HoSiawEng,HoSiawEng,Elly,HoSiawEng,HoSiawEng,Elly,TimothyKwan,Elly,TimothyKwan,Elly,Elly

In [108]:
def test_skill_match(solution_df, skills_df):
    temp_df = solution_df.set_index('Job')  # Set 'Job' as index

    for job in temp_df.index:
        people = temp_df.loc[job].dropna().values  # Get assigned people

        # Check if they have the required skills
        invalid_people = [person for person in people if not skills_df.loc[person, job]]
        
        assert not invalid_people, f"People without required skills for {job}: {invalid_people}"

In [109]:
test_skill_match(flawed_solution_df, skills_df)

AssertionError: People without required skills for Coordinator(M): ['Jeffrey']